const cfg=window.APP_CONFIG||{};
const configured=cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY;
const supabaseClient=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let items=[], profile={perfil:'visualizador'};
const $=id=>document.getElementById(id);
const statuses=['Planejamento','Cotando','Cotado','Aguard. Autorização','Enviado p/ Licitação','Edital Publicado','Concluído','Suspenso','Cancelado'];
statuses.forEach(s=>$('statusFilter').insertAdjacentHTML('beforeend',`<option>${s}</option>`));
function brDate(v){if(!v)return '—';const [y,m,d]=v.slice(0,10).split('-');return `${d}/${m}/${y}`}
function money(v){return v==null||v===''?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function enriched(x){const overdue=x.data_limite_planejamento&&!x.data_envio_licitacao&&new Date(x.data_limite_planejamento+'T23:59:59')<new Date()&&!['Concluído','Cancelado','Suspenso'].includes(x.situacao_geral);return {...x,overdue}}
function filtered(){const q=$('search').value.trim().toLowerCase(),s=$('statusFilter').value,c=$('quoteFilter').value;return items.map(enriched).filter(x=>(!q||[x.demanda,x.secretaria,x.responsavel,x.modalidade_prevista].some(v=>(v||'').toLowerCase().includes(q)))&&(!s||x.situacao_geral===s)&&(!c||x.situacao_cotacao===c))}
function render(){const list=filtered();$('tbody').innerHTML=list.map((x,i)=>`<tr class="${x.overdue?'overdue-row':''}"><td>${x.numero??i+1}</td><td><div class="demand-name">${esc(x.demanda)}</div>${x.observacoes?`<small class="muted">${esc(x.observacoes)}</small>`:''}${x.impedimentos?`<small class="muted">Impedimento: ${esc(x.impedimentos)}</small>`:''}</td><td>${esc(x.secretaria||'—')}</td><td>${esc(x.tipo_objeto||'—')}</td><td>${esc(x.modalidade_prevista||'—')}</td><td>${esc(x.situacao_cotacao||'—')}</td><td>${brDate(x.data_inicio_planejamento)}</td><td>${brDate(x.data_limite_planejamento)} ${x.overdue?'<span class="badge atrasado">Atrasado</span>':''}</td><td>${brDate(x.data_envio_licitacao)}</td><td class="money">${money(x.valor_estimado)}</td><td>${esc(x.responsavel||'—')}</td><td><span class="badge ${x.situacao_geral==='Concluído'?'ok':x.situacao_geral==='Suspenso'||x.situacao_geral==='Cancelado'?'warn':''}">${esc(x.situacao_geral||'Sem status')}</span></td><td><div class="actions editor-only"><button class="ghost" onclick="editItem('${x.id}')">Editar</button><button class="ghost admin-only" onclick="deleteItem('${x.id}')">Excluir</button></div></td></tr>`).join('');$('emptyState').classList.toggle('hidden',list.length>0);renderKpis();applyRole()}
function renderKpis(){const all=items.map(enriched),active=all.filter(x=>!['Concluído','Cancelado','Suspenso'].includes(x.situacao_geral));const k=[['Carteira ativa',active.length],['Em cotação',all.filter(x=>x.situacao_cotacao==='Cotando').length],['Enviadas à licitação',all.filter(x=>x.data_envio_licitacao).length],['Concluídas',all.filter(x=>x.situacao_geral==='Concluído').length],['Atrasadas',all.filter(x=>x.overdue).length]];$('kpis').innerHTML=k.map(([a,b])=>`<div class="kpi"><small>${a}</small><b>${b}</b></div>`).join('')}
function applyRole(){document.querySelectorAll('.editor-only').forEach(el=>el.classList.toggle('hidden',!['administrador','editor'].includes(profile.perfil)));document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',profile.perfil!=='administrador'))}
async function loadProfile(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {data,error}=await supabaseClient.from('perfis').select('perfil,nome,ativo,modulo_planejamento').eq('id',user.id).single();if(error)throw error;profile=data||{perfil:'visualizador'};if(!profile.ativo||!profile.modulo_planejamento)throw new Error('Usuário sem acesso ao módulo Planejamento.');$('userBadge').textContent=`${profile.nome||user.email} · ${profile.perfil}`}
async function loadItems(){const {data,error}=await supabaseClient.from('planejamentos').select('*').order('numero',{ascending:true});if(error)throw error;items=data||[];render()}
async function boot(){if(!configured){$('loginMsg').textContent='Projeto ainda não conectado ao Supabase.';return}const {data:{session}}=await supabaseClient.auth.getSession();if(session){try{await enterApp()}catch(e){$('loginMsg').textContent=e.message;await supabaseClient.auth.signOut()}}supabaseClient.auth.onAuthStateChange((_e,s)=>{if(!s){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}})}
async function enterApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await loadProfile();await loadItems()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='';const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent='Não foi possível entrar. Confira e-mail e senha.';return}try{await enterApp()}catch(err){$('loginMsg').textContent=err.message;$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');await supabaseClient.auth.signOut()}});
$('logoutBtn').onclick=()=>supabaseClient.auth.signOut();['search','statusFilter','quoteFilter'].forEach(id=>$(id).addEventListener('input',render));$('clearFilters').onclick=()=>{$('search').value='';$('statusFilter').value='';$('quoteFilter').value='';render()};$('printBtn').onclick=()=>window.print();
$('exportBtn').onclick=()=>{const data=filtered().map(x=>({'Nº':x.numero,'Demanda':x.demanda,'Secretaria':x.secretaria,'Tipo de Objeto':x.tipo_objeto,'Modalidade Prevista':x.modalidade_prevista,'Situação da Cotação':x.situacao_cotacao,'Início':brDate(x.data_inicio_planejamento),'Data Limite':brDate(x.data_limite_planejamento),'Envio à Licitação':brDate(x.data_envio_licitacao),'Valor Estimado':x.valor_estimado,'Responsável':x.responsavel,'Situação Geral':x.situacao_geral,'Impedimentos':x.impedimentos,'Observações':x.observacoes}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Planejamento');XLSX.writeFile(wb,'planejamento_filtrado.xlsx')};
function openDialog(x={}){const map={itemId:'id',f_nome:'demanda',f_secretaria:'secretaria',f_tipo:'tipo_objeto',f_modalidade:'modalidade_prevista',f_cotacoes:'situacao_cotacao',f_inclusao:'data_inicio_planejamento',f_limite:'data_limite_planejamento',f_envio:'data_envio_licitacao',f_valor:'valor_estimado',f_responsavel:'responsavel',f_status:'situacao_geral',f_impedimentos:'impedimentos',f_obs:'observacoes'};Object.entries(map).forEach(([id,k])=>$(id).value=x[k]??'');if(!x.id){$('f_inclusao').value=new Date().toISOString().slice(0,10);$('f_status').value='Planejamento'}$('dialogTitle').textContent=x.id?'Editar demanda':'Nova demanda';$('itemDialog').showModal()}
$('newBtn').onclick=()=>openDialog();$('closeDialog').onclick=$('cancelBtn').onclick=()=>$('itemDialog').close();window.editItem=id=>openDialog(items.find(x=>String(x.id)===String(id)));window.deleteItem=async id=>{if(!confirm('Excluir esta demanda?'))return;const {error}=await supabaseClient.from('planejamentos').delete().eq('id',id);if(error)return alert(error.message);await loadItems()};
$('itemForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('itemId').value;const payload={demanda:$('f_nome').value.trim(),secretaria:$('f_secretaria').value.trim()||null,tipo_objeto:$('f_tipo').value||null,modalidade_prevista:$('f_modalidade').value.trim()||null,situacao_cotacao:$('f_cotacoes').value||null,data_inicio_planejamento:$('f_inclusao').value||null,data_limite_planejamento:$('f_limite').value||null,data_envio_licitacao:$('f_envio').value||null,valor_estimado:$('f_valor').value===''?null:Number($('f_valor').value),responsavel:$('f_responsavel').value.trim()||null,situacao_geral:$('f_status').value||null,impedimentos:$('f_impedimentos').value.trim()||null,observacoes:$('f_obs').value.trim()||null};let res;if(id)res=await supabaseClient.from('planejamentos').update(payload).eq('id',id);else res=await supabaseClient.from('planejamentos').insert(payload);if(res.error)return alert(res.error.message);$('itemDialog').close();await loadItems()});
boot();
