-- Dados importados de Controle_Processos_Planejamento_1 (1).xlsx
insert into public.planejamentos
(numero,nome_demanda,secretarias,tipo_objeto,modalidade_prevista,situacao_cotacoes,qtd_cotacoes,data_inclusao,prazo_interno,data_envio_licitacao,data_publicacao_edital,valor_estimado,responsavel_interno,situacao_geral,observacoes)
values
(1,'Manutenção de Impressora','Município','Serviço','Credenciamento','Cotado',3,'2026-06-08',20,'2026-07-20',null,null,null,'Enviado p/ Licitação',null),
(2,'Rádio e Carro de Som','Sec. Administração','Serviço','Credenciamento','Cotado',1,'2026-06-15',20,'2026-07-20',null,null,null,'Enviado p/ Licitação',null),
(3,'Painel de LED','Sec. Educação','Bem','Pregão Eletrônico','Cotando',null,'2026-03-18',20,null,null,null,null,'Planejamento','Reenviar email'),
(4,'Toldos','Sec. Educação','Bem','Pregão Eletrônico','Cotado',1,'2026-03-18',20,'2026-07-15',null,null,null,'Enviado p/ Licitação',null),
(5,'Camisa (Felise)','Sec. Educação','Bem','Pregão Eletrônico','Cotado',1,'2026-06-17',20,'2026-07-15',null,null,null,'Enviado p/ Licitação',null),
(6,'Móveis fracassados (Convenio)','Municipio','Bem','Pregão Eletrônico','Cotado',1,'2026-07-03',20,null,null,null,null,'Enviado p/ Licitação','Maira solicitou cotacao local e esta aguardando'),
(7,'Vidro (janelas e afins)','Sec. Obras / Municipio','Bem','Pregão Eletrônico','Cotado',3,'2026-02-09',20,'2026-07-20',null,null,null,'Enviado p/ Licitação',null),
(8,'Sistema da Educação','Sec. Educação','Serviço','Pregão Eletrônico','Cotado',1,'2026-06-01',20,'2026-07-13',null,null,null,'Enviado p/ Licitação','Romulo Imap,'),
(9,'Banco (Praça)','Sec. Obras','Obra','Pregão Eletrônico','Cotado',3,'2026-07-03',20,'2026-07-08',null,null,null,'Enviado p/ Licitação',null),
(10,'Diagnostico por imagem','Sec. Saúde','Serviço','Credenciamento','Cotando',1,'2026-07-07',20,null,null,null,null,'Planejamento','Banco de preco - Monica -'),
(11,'Imunoglobulina','Sec. Saúde','Bem','Dispensa','Cotado',3,'2026-07-07',20,'2026-07-15',null,null,null,'Enviado p/ Licitação',null),
(12,'Asfalto','Sea. Obras','Bem','Contrato Direto','Cotado',3,'2026-07-07',20,'2026-08-07',null,null,null,'Enviado p/ Licitação',null),
(13,'IBDM - Publicações','Municipio','Serviço','Pregão Eletrônico','Planejamento',null,null,null,null,null,null,null,null,null),
(14,'Asfalto 200T','Sec. Obras / Municipio','Obra','Pregão Eletrônico','Cotado',null,'2026-07-07',5,'2026-08-07',null,null,null,'Enviado p/ Licitação',null),
(15,'Instr. Equip. Ondont','Sec. Saúde','Serviço','Pregão Eletrônico','Cotando',null,'2026-07-13',20,null,null,null,null,null,null),
(16,'Recarga Impressora','Sec. Administração','Serviço','Pregão Eletrônico','Planejamento',null,null,20,null,null,null,null,null,null),
(17,'Mat. Limpeza (Lote Royal)','Município','Bem','Pregão Eletrônico','Planejamento',null,null,null,null,null,null,null,null,null),
(18,'Medicamentos (fracassados)','Sec. Saúde','Bem','Pregão Eletrônico','Cotado',null,'2026-07-14',null,'2026-07-21',null,null,null,'Enviado p/ Licitação',null),
(19,'Mat. De Construção (fracassados)','Sec. Obras','Bem','Pregão Eletrônico','Cotando',null,'2026-07-27',null,null,null,null,null,null,null),
(20,'Botas agente (fracassados)','Sec. Saúde','Bem','Dispensa','Cotado',null,'2026-07-20',null,'2026-07-24',null,null,null,'Enviado p/ Licitação',null),
(21,'Extintores de Incêndio','Município','Bem','Pregão Eletrônico','Cotado',null,'2026-07-20',null,'2026-07-23',null,null,null,'Enviado p/ Licitação',null),
(22,'kit identidade','Sec. Administração','Bem','Contrato Direto','Cotado',null,'2026-07-20',null,'2026-07-22',null,null,null,'Enviado p/ Licitação',null),
(23,'Carimbo e Encadernação','Município','Serviço','Dispensa','Cotado',null,'2026-07-21',null,'2026-07-30',null,null,null,'Enviado p/ Licitação',null),
(24,'Balança digital','Sec. Saúde','Bem','Dispensa','Cotado',null,'2026-07-24',null,'2026-07-24',null,null,null,'Enviado p/ Licitação',null),
(25,'Arla',null,'Bem',null,'Planejamento',null,'2026-08-15',20,null,null,null,null,null,null),
(26,'Tacográfos',null,'Bem',null,'Planejamento',null,'2026-08-17',20,null,null,null,null,null,null),
(27,'Proteina animal PNAE','Sec. Educação','Bem','Dispensa','Cotado',null,'2026-07-20',null,'2026-07-27',null,null,null,'Enviado p/ Licitação',null),
(28,'Ornamentação natalina','Sec. Cultura','BEM',null,'Cotando',2,'2026-07-27',null,null,null,null,null,null,null),
(29,'Man. de eletronicos',null,null,null,null,null,null,null,null,null,null,null,null,null),
(30,'Ser. De Chaveiro',null,null,null,null,null,null,null,null,null,null,null,null,null),
(31,'Itens para castracao','Sec. Saúde',null,null,null,null,null,null,null,null,null,null,null,null),
(32,'Medicamentos veterinários','Sec. Saúde','Bem','Contrato Direto','Cotado',null,'2026-07-30',null,'2026-08-04',null,null,null,'Enviado p/ Licitação',null),
(33,'Kit alimewntação escolar','Sec. Educação','Bem','Contrato Direto','Cotado',null,'2026-08-05',null,'2026-08-05',null,null,null,'Enviado p/ Licitação',null),
(34,'Curso Assistência Social','Sec. Assistencia Social','Serviço','Inexigibilidade',null,null,null,null,null,null,null,null,null,null),
(35,'Fralda descartável','Município',null,null,null,null,null,null,null,null,null,null,null,null),
(36,'Man. Geladeira','Sec. Educação',null,'Contrato Direto','Cotado',null,'2026-08-13',null,'2026-08-13',null,null,null,'Enviado p/ Licitação',null);

select setval(pg_get_serial_sequence('public.planejamentos','numero'), greatest((select max(numero) from public.planejamentos),1));
