-- Execute no SQL Editor do Supabase.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'viewer' check (role in ('admin','editor','viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.planejamentos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  nome_demanda text not null,
  secretarias text,
  tipo_objeto text,
  modalidade_prevista text,
  situacao_cotacoes text,
  qtd_cotacoes integer,
  data_inclusao date,
  prazo_interno integer default 20,
  data_envio_licitacao date,
  data_publicacao_edital date,
  valor_estimado numeric(14,2),
  responsavel_interno text,
  situacao_geral text,
  observacoes text,
  criado_por uuid references auth.users(id),
  atualizado_por uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.planejamento_historico (
  id bigint generated by default as identity primary key,
  planejamento_id uuid,
  acao text not null,
  dados jsonb,
  usuario_id uuid,
  criado_em timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.planejamentos enable row level security;
alter table public.planejamento_historico enable row level security;

create policy "perfil próprio leitura" on public.profiles for select to authenticated using (id=auth.uid());
create policy "planejamentos leitura autenticada" on public.planejamentos for select to authenticated using (true);
create policy "planejamentos inserir editor" on public.planejamentos for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','editor')));
create policy "planejamentos atualizar editor" on public.planejamentos for update to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','editor'))) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','editor')));
create policy "planejamentos excluir admin" on public.planejamentos for delete to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "historico leitura autenticada" on public.planejamento_historico for select to authenticated using (true);

create or replace function public.set_audit_fields() returns trigger language plpgsql security definer as $$
begin
  if tg_op='INSERT' then new.criado_por=auth.uid(); end if;
  new.atualizado_por=auth.uid(); new.updated_at=now(); return new;
end $$;
create trigger trg_planejamento_audit before insert or update on public.planejamentos for each row execute function public.set_audit_fields();

create or replace function public.log_planejamento_change() returns trigger language plpgsql security definer as $$
begin
  insert into public.planejamento_historico(planejamento_id,acao,dados,usuario_id)
  values(coalesce(new.id,old.id),tg_op,case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end,auth.uid());
  return coalesce(new,old);
end $$;
create trigger trg_planejamento_history after insert or update or delete on public.planejamentos for each row execute function public.log_planejamento_change();
